### ISSUE TITLE
How to enable analytics feature?

### ISSUE THREAD

**Issue by yiikou** [smartshark/visualSHARK#35]
Hi, I notice several fancy features under the analtyics tab. For example, Defect Links, product stats, prediction and release finder.  

So, may I ask  that:
1.  How can I use these features? 
2. What is the issue block in Project veiew?
![image](https://user-images.githubusercontent.com/6872777/98627948-702f4a00-22e3-11eb-999c-7037b12d4b18.png)
3. And I also curious, is the result from linkSHARK will appear in defect links? Or that is the visualization for inducingSHARK?

Additionally, when I execute `python manage.py create_git_stats PROJECT`, it shows 
```
[OK] Getting Stats for Project commons-rdf (5faa0b4aeb751680a8a4100e)
{'authors': 26,
 'avg_authors_per_file': 1.5360360360360361,
 'code_files_renamed': 595,
 'code_lines': 273766,
 'code_lines_added': 321344,
 'code_lines_deleted': 47578,
 'files_added': 3652,
 'files_copied': 191,
 'files_deleted': 129,
 'files_modified': 4841,
 'files_renamed': 683,
 'other_lines': 45461,
 'other_lines_added': 55714,
 'other_lines_deleted': 10253,
 'tags': ['0.5.0-RC3',
          '0.5.0',
          '0.5.0-RC1',
          '0.3.0-incubating',
          '0.2.0-incubating',
          '0.1.0-incubating',
          'apache-import-20150327',
          '0.0.2',
          '0.0.1']}
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/visualSHARK/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/visualSHARK/visualSHARK/management/commands/create_git_stats.py", line 149, in handle
    ret = self.get_version_tags(vcs_id)
  File "/visualSHARK/visualSHARK/management/commands/create_git_stats.py", line 38, in get_version_tags
    versions = tag_filter(Tag.objects.filter(vcs_system_id=vcs_id), discard_qualifiers=True, discard_patch=True)
TypeError: tag_filter() missing 1 required positional argument: 'tags'
```
4. How should I fix this?
5. The labeling feature looks awesome! (https://smartshark.github.io/msr20_registered_report/) and I also notice the labeling tab. Can I also use this feature?
6. Is the result of changeSHARK can also be visualized here?

Thank you!

**Comment by atrautsch** [comment]
Much of the analytics section contains exploratory ad-hoc code. Some views do not display data from the MongoDB directly but compute some data itself.

1. Defect links should be usable although it displays defect links that are generated by visualSHARK itself on-the-fly not directly from the MongoDB.
I used that to explore different approaches a bit.
Product stats and prediction are views that use release level defect prediction data generated by [Mynbou](https://github.com/smartshark/mynbou). It is also exploratory in nature and at the moment we use jupyter notebooks to explore the data which is more flexible.
The release finder should work, it tries to distinguish project releases from other git tags of the project. The results are generated on-the-fly and not persisted in the database. The main purpose here was also to explore different settings for detecting project releases from all tags.

2. The project view contains test-code from the integration of the monaco editor for the labeling feature. I will remove that in the next days.

3. Defect links is purely exploratory, the results from inducingSHARK and linkSHARK are visible in the commit view.

4. The git statistics is also an exploratory feature which collects some additional statistics. The command is  also exploratory in nature. I will update visualSHARK with a fix for the function.

5. The labeling feature should be usable. I merged the line_labels branch into master so it should be available on your next pull.
If you pull, we may have included database upgrades so you need to run manage.py migrate again to apply the changes.

6. The changeSHARK result is currenly not visible, I will probably include it in the commit view as it labels changes.

**Comment by yiikou** [comment]
I updated! According to the pop-up diaglog, I can select project to do manual label. But I cannot see anything in the dropdown under `manual labels`. So what is the "available" project here?

I further execute one more command `python manage.py create_issue_validation` and there is some content in `issue types` now. How do I also enable `issue type conflicts` and `commit->issue`?

**Comment by atrautsch** [comment]
Manual labels should show the manual validation view. If you are logging in as the superuser you should be able to see everything.
The popup speaks of the project dropdown on the right, although we have never tested this outside of our own deployment.
The line labeling may not work out of the box, there are for example hard coded training issues which would not be available in other databases. It also requires manually validated issue types so to use that feature there would be some changes in the code necessary.

Issue type conflicts shows only the issues where 2 users decided on a different label. This is also not really tested outside our own deployment. We would probably have to make parameters configurable, e.g., the number of users that are needed for labeling, the types of labels or when consensus is achieved.

**Comment by yiikou** [comment]
Thanks for the clarification. 

I also find that, 1) there seems no page control in `issue type` and `commit->issue`. One page only show 10 entities, while there are much more. 2) Where does the labeled issue go? When I select label, and click submit. I cannot find them anymore. 3) What does the `verification` mean? Does it mean once checked, the label will be shown in issues tab?

May I also ask that which project are you using to test the SZZ feature?
The `commit->issue` looks neat. But according to my result, 
![image](https://user-images.githubusercontent.com/6872777/98701009-d26d6680-2346-11eb-9e95-2fa40458b6cd.png) seems the linkage is created simply by regular expression. I wish to check this SZZ result as well.

**Comment by yiikou** [comment]
One more thing would like to confirm, is the data in `manual labels` comes from labelSHARK, or the script `create_issue_validation.py`? For now, the default label result look not good. Baically all issues' labels are "other".

**Comment by atrautsch** [comment]
1+2) Both are not build with the usual grid so there is no pagination available. In our use case this was not a problem as we needed to verify everything for a project anyways. The label is written in the MySQL database, it does not show anymore for your user because you assigned your label. If you login with another user you should see it again. Our use case was two users independently label the issue type and if there are conflicts they are shown in the conflict view.
3) The verification checkbox indicates that the user manually verified the label that he chose for the issue, only issues where the checkbox is checked are saved.

The commit issue links are prepopulated from the linkSHARK which uses a set of regex to find issues in commit messages.
They are manually validated in the commit->issue links view and then written back to the MongoDB as fixed_issue_ids list for each commit.

**Comment by yiikou** [comment]
Is lilnkSHARK only use regex to find issues? I notice an error message in [linkSHARK/linkshark.py](https://github.com/smartshark/linkSHARK/blob/master/linkSHARK/linkshark.py) lin 89, `index error because SZZ currently only support JIRA, may not link all issues correctly`. Does it mean SZZ will be used for JIRA issues?

**Comment by atrautsch** [comment]
Manual labels is just the overall category. 
The commit->issue links are from the linkSHARK.
The issue types are from the create_issue_validation command, they simply create the MySQL overlay tables so that multiple users can label them. And we can write back the consensus label to the MongoDB or view them in the conflict view.
In the issue type view the prepopulated issue types are directly taken from the issue themselves. If you want to test that I would recommend a project which uses Jira because that should probably match our types quite closely.

**Comment by yiikou** [comment]
Thanks, I think my previous question is also answered.

**Comment by yiikou** [comment]
Hi @atrautsch , I'm SUPER interested in the prediction feature (even if it is not as flexible as using jupyter notebook, it completes the last valve of analysis pipeline). As I understand, this feature rely on data generated from Mynbou and Mynbou is not supported by serverSHARK for now. I'm curious that how can I connect Mynbou and the prediction feature? Will Mynbou will write data to mongodb, and the data will further to be used by the prediction feature. Or Mynbou will generate a file, and I need to somehow import it to visualSHARK's MySQL db?

Sorry that I'm still testing the last plugin (refSHARK) that are required by Mynbou, hence I cannot try it out myself.

**Comment by atrautsch** [comment]
Hi @yiikou is there a specific use case you are thinking about?
It would not be much effort to integrate a defect prediction approach into visualSHARK so that we could use previous releases of the current project for training and evaluating risk on the current release. However, the question of the best approach is still a topic of research. The evaluation of such an approach would also entail to some extend changing features or using a different szz variant for commit to issue links or even rename tracking of files. That part is not a good fit for integration into a project as visualSHARK as the possible options for even a simple approach are too broad in my opinion.

However, while exploration of approaches is probably difficult if an approach is chosen it can simply be integrated.
At the moment Mynbou is independent of serverSHARK and writes extra files for release level defect prediction data. In a previous version those were also stored in the MongoDB to be used by visualSHARK prediction view via the MongoDB GridFS. 

This is how that looks with a small project in our data:
![predict_view](https://user-images.githubusercontent.com/5121615/98817358-49c7f680-242a-11eb-994e-76de581bfdf9.png)
![product_view](https://user-images.githubusercontent.com/5121615/98817362-4a608d00-242a-11eb-96b9-8618ca88d3cb.png)

As you can see for the product view there is a categorization of the files and how the clean/buggy files are distributed. This is one specific use case which we were evaluating at the time.
The prediction view shows the evaluation, after selecting the training and test data you can choose between a naive bayes model and a random forest. It can also show the prediction and true values for each file of the test data. 

As you may note from the date this feature is pretty old and we changed Mynbou since then. I will try to find the code which uploads the Mynbou results into the MongoDB for visualSHARK.

**Comment by yiikou** [comment]
Hi @atrautsch , thanks for the detailed explanation! And my use case is to predict defects of the current release version. I notice that in the first figure, there has `predict result`, which is empty. Does it mean that there is no defect in your current release?

I'm also thinking about that, currently, each plugin has dependencies with each other, loosely, and not support batch execution (execute multiple plugins in order in one operation). If the orchestration of plugins pipeline (where we can arrange the plugin order and setup extend changing feature) and the Mynbou can be integrated together, the exploration of approaches will be low cost.

And finally, I got every necessary plugin running! Thank you for the help. Now I can use Mynbou to generate data. Can wait to try **prediction** feature! Does the uploading code exist in the current repository or? If so, I can help to find that. (I really cannot wait to try it :-p

**Comment by sherbold** [comment]
FYI: we also have a release level data set with all the data we have collected and validated that you can use (398 releases, 38 projects, if I remember correctly). All available as csv files :-)

https://arxiv.org/abs/1911.08938

**Comment by yiikou** [comment]
@sherbold awesome, thank you! I assume these data can also be used in visualSHARK prediction feature, right? (once they are uploaded)

**Comment by sherbold** [comment]
I am not sure and, frankly, doubt this, but @atrautsch knows this better than me. We implemented the prediction feature in the VisualSHARK as a proof-of-concept for an industrial partner, when we had an early version of Mynbou. This early version evolved a bit during the work on the article, e.g., to fully support the bug matrix and enable to account for all temporal dependencies within the data. You can find a sample on how to use that data with scikit-learn (and visualize results) in the replication notebook of the "Issues with SZZ" paper.

**Comment by yiikou** [comment]
Thanks for the clarification  and suggestion! @sherbold

**Comment by atrautsch** [comment]
@yiikou I have upgraded Mynbou and visualSHARK. You can now enable the storage of the Mynbou results back into the MongoDB with --save-to-mongo and the visualSHARK is now able to display them in the product information and prediction view.
Depending on project size this takes some time and the loading indicator may not fully work because in the newer Mynbou version we have a lot more features than in the old version. It should work in a reasonable time on smaller projects.

**Comment by yiikou** [comment]
> Manual labels is just the overall category.
> The commit->issue links are from the linkSHARK.
> The issue types are from the create_issue_validation command, they simply create the MySQL overlay tables so that multiple users can label them. And we can write back the consensus label to the MongoDB or view them in the conflict view.
> In the issue type view the prepopulated issue types are directly taken from the issue themselves. If you want to test that I would recommend a project which uses Jira because that should probably match our types quite closely.

Hi @atrautsch, I would like to further confirm some logic of manual labeling.
1) We use `create_issue_validation` to create data for manual labeling. Seems the "label" here, means the "type" in jira?

2)After solving conflict (or there is no conflict for two users). I run `calculate_issue_validation` and it sync labeling result back to mongodb. And the verified type field is updated. I wonder is it the correct operation?
![image](https://user-images.githubusercontent.com/6872777/99031869-1e3a2e80-2546-11eb-8274-a5f639084d82.png)

3) In the commit view, what is the manual verifications, and validated links?
![image](https://user-images.githubusercontent.com/6872777/99031936-4164de00-2546-11eb-8a9c-a785162a19fe.png)

4) In the commit-link, the revision address is svn address. How can I convert it to git SHA?
![image](https://user-images.githubusercontent.com/6872777/99032174-df58a880-2546-11eb-85de-ad050e8e9899.png)

Thank you.

**Comment by atrautsch** [comment]
1) The label that is assigned is the type in Jira or a mapped type in our case. We map existing Jira types to a defined list of types we use.
2) That is correct.
3) Manual verifications is a list of labels for a commit which kind of manual validation was done. It should contain a label when the  commit-issue link has been verified.
4) The git-svn-id is in some projects  part of the commit message, the commits still contain a sha hash it is just not displayed in that view. 
5) The issue link candidates is an evaluation view to allow us to manually check some approaches. It does not use the MongoDB other than fetching commit/issue information and the link. The inducingSHARK data is visible in the commit view for bug-inducing commits although there currently exists nor visible link in the visualSHARK from bug-fixing to bug-inducing commits.
