### ISSUE TITLE
How to read the commit graph

### ISSUE THREAD

**Issue by yiikou** [smartshark/visualSHARK#36]
Hi, I would like to learn how to read the commit graph as follows:
![image](https://user-images.githubusercontent.com/6872777/99215657-994b5100-27a1-11eb-8feb-9214c30b2655.png)

Especially:
1) the meaning of the legend (e.g., path. nr.0).
2) the meaning of articulation points (the dark big green point).

Thank you.

**Comment by atrautsch** [comment]
I implemented the paths feature to visually evaluate the approach better.
The legend with the path numbers basically enumerates paths which can be split off, e.g., a feature branch. It is basically a breadth-first search which enumerates all commits and creates a new path for every split, e.g., creation of a branch.
The articulation points mark the points which can be used to split the whole graph into two graphs.

The search in commit messages is used for some validations in our work. The view options also allow tying in additional information, e.g, all commits for which travis builds failed via the travisSHARK. It can also restrict the visible commits via commit labels from the labelSHARK however for that the command fetch_commit_label_approaches needs to run because that fetches all available labels from the MongoDB and stores it in the MySQL.

**Comment by yiikou** [comment]
Thanks for the explanatoin!
